### ISSUE TITLE
Datetime to timestamp translations may results in unintended time slips

### ISSUE THREAD

**Issue by radu-stefan-dt** [dynatrace-oss/api-client-python#43]
`int64_to_datetime` and `datetime_to_int64` from `dynatrace.utils` may result in unwanted time differences when gathering Dynatrace objects with timestamp details and then converting back into JSON or sending back to Dynatrace.

int64_to_datetime
* is used everywhere when taking in a JSON that has timestamps and turning into a `DynatraceObject`
* it uses `datetime.utcfromtimestamp()` method which gives a datetime object interpreting the timestamp as UTC, however, the created datetime object does not carry timezone information (is naive, not aware).
* this means, next time I do datetime to int, my datetime will be converted to the int64 representing the datetime in my PC's local timezone.
* https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp

datetime_to_int64
* is used when doing the to_json() translation - for example - before sending a `DynatraceObject` as payload to dynatrace
* this relies on the timestamp argument to already carry the timezone information set to UTC (to match Dynatrace's expectation)
* however, if the user only used our framework to work with these objects, this will not result in the correct int64 value
* https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp

I propose UTC is kept all throughout the framework to keep times sync'ed with Dynatrace API expectations/formats.

Existing code:
```python
def int64_to_datetime(timestamp: Optional[int]) -> Optional[datetime]:
    if timestamp is None or not timestamp:
        return None
    return datetime.utcfromtimestamp(timestamp / 1000)


def datetime_to_int64(timestamp: Optional[datetime]) -> Optional[int]:
    if not isinstance(timestamp, datetime):
        return timestamp
    return timestamp.timestamp() * 1000
```

Proposed changes:
```python
from datetime import timezone

...

def int64_to_datetime(timestamp: Optional[int]) -> Optional[datetime]:
    if timestamp is None or not timestamp:
        return None
    return datetime.fromtimestamp(timestamp / 1000, timezone.utc)


def datetime_to_int64(timestamp: Optional[datetime]) -> Optional[int]:
    if not isinstance(timestamp, datetime):
        return timestamp
    return timestamp.replace(tzinfo=timezone.utc).timestamp() * 1000
```

**Comment by dlopes7** [comment]
Thanks a lot @radu-stefan-dt  I agree that we should follow the API specs and always use UTC, very nice catch
