### ISSUE TITLE
Exception returned when getting notification config that references deleted alerting profile

### ISSUE THREAD

**Issue by Dynatrace-James-Kitson** [dynatrace-oss/api-client-python#51]
I'll be fixing this but I came across an issue where as part of gathering problem notifications currently it uses the alerting profile id to make a call and get the full alerting profile configuration. The issue is that if an alerting profile is deleted, the notification still refers to that ID but if you make the call to look it up it returns a 404 which causes getting the whole notification to fail with an exception.

https://github.com/dynatrace-oss/api-client-python/blob/23c8e2cc720f05b00f7fa5e1d63b7eb3670d8261/dynatrace/configuration_v1/notifications.py#L31-L33

```
Exception: Error making request to https://example.com/api/config/v1/alertingProfiles/7693d108-fda9-3529-8ca3-55e9269b6097: <Response [404]>. Response: {"error":{"code":404,"message":"Could not find config 7693d108-fda9-3529-8ca3-55e9269b6097."}}
```

I see two ways of fixing this:

1. Handle the exception when initializing the Notification object and set the alerting profile to None. This has the benefit of keeping the feature of automatically pulling in the profile details (when they exist) for notifications when listing them.
2. Revert to instead just reporting the string alerting profile ID when creating the notification object and then it is up to the user to make a call and get the profile details if they want them and handling if a 404 is returned.

As of now I'm leaning towards 1.

**Comment by Dynatrace-James-Kitson** [comment]
Another consideration is if we just return None the user wouldn't even know what the original ID was. Even though that may be of limited value since you can't look up the name anymore even it at least could be a tool if they're doing some auditing. So returning the str may be the most flexible in the end although it could possibly break some things if people were using the old approach (though I doubt this would be common).

**Comment by dlopes7** [comment]
That create_from_raw_data method calling a different API looks super weird indeed, I think the notifications implementation might be a bit convoluted at the moment, we should follow exactly what the API specifies, and not come up with ideas of returning None, or calling different APIs, I will review the code later today to think about how to update it

**Comment by Dynatrace-James-Kitson** [comment]
Yeah, I can make some updates to just return the string value for the ID like API specifies and you can decide if that works or if need to do anything more complicated.
