### ISSUE TITLE
Implementation Progress up-to-dateness

### ISSUE THREAD

**Issue by barthduthoit** [dynatrace-oss/api-client-python#54]
I was wondering about the freshness of the "Implementation Progress" tables of the Readme: does it reflect the current status of all API routes ?
For instance, I see that `Alerting Profiles` (under Configuration API V1) is marked as ❌, but I also see that [`alerting_profiles.py`](https://github.com/dynatrace-oss/api-client-python/blob/main/dynatrace/configuration_v1/alerting_profiles.py) implements the connection to the `alertingProfiles` endpoint.

**Comment by Dynatrace-James-Kitson** [comment]
Thank you for making note of that, we'll go through and check to make sure the progress table reflects true coverage.
