### ISSUE TITLE
Add support for events ingestion

### ISSUE THREAD

**Issue by gabrielprioli** [dynatrace-oss/api-client-python#63]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implementation of the `/api/v2/events/ingest` endpoint 

**Describe alternatives you've considered**
I'm already using the library for metrics ingestion and logs ingestion, so the alternative would be to create the HTTP client from scratch only to interact with this endpoint, which is not really desirable.

**Additional context**
I'm developing an integration from Oracle Cloud to Dynatrace

**Comment by Dynatrace-James-Kitson** [comment]
Seems like an important one to include, will look at doing that soon.

In the meantime, if there's any urgency you could temporarily use the v1 events endpoint for which ingestion is already implemented, would need to refactor it once switch to v2 though but should be pretty similar.
