### ISSUE TITLE
Please support mzSelector

### ISSUE THREAD

**Issue by ToTru** [dynatrace-oss/api-client-python#72]
**Is your feature request related to a problem? Please describe.**
I need to calculate DEM consumption based on some billing metrics. Today I have to bother the system with a set of queries, one per Type. If mzSelector of the metric API could be used, I could omit the entitySelector, which forces to set the type. One single query would be enough.

**Describe the solution you'd like**
Extent metric.py by an additional Parameter.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Dynatrace-James-Kitson** [comment]
This is included in 1.1.61 which was just pushed to pypi.

**Comment by ToTru** [comment]
Thanks a lot James!Am 16.05.2023 um 23:01 schrieb James Kitson ***@***.***>:﻿
Hi @ToTru, this looks like an easy and useful thing to add so I'll plan on adding it as soon as I can.
