### ISSUE TITLE
Add monitored_entity type field

### ISSUE THREAD

**Issue by Dynatrace-Jeroen-Hautekeete** [dynatrace-oss/api-client-python#85]
The type for most monitored entities can be determined by the start of the entityId.
However for custom devices, the additional field "type" should be used.

The class EntityId (used in relationships) already holds this field, but it would be useful in class Entity also.

**Comment by Dynatrace-James-Kitson** [comment]
This project is a client for interacting with the API, what you're asking for is capabilities that would fit into the API itself. When using this client you have to work within the framework of the API - everything (supported) that can be done in the API directly we can do in the client.

In this case you haven't specified what call you're talking about, this type information is already available in the entities list call which is the only one I can think you're referring to:

```
for entity in dt.entities.list("type(remote_unix:host)"):
    print(entity)

>> Entity({'displayName': 'ubuntu-dev-ag', 'entityId': 'CUSTOM_DEVICE-B9DD28272B3E3C91', 'type': 'remote_unix:host'})
```

**Comment by Dynatrace-James-Kitson** [comment]
Assuming you're talking about the v2 `dt.entities.list(...)` it looks like this is just an oversight and is quick to add.

**Comment by Dynatrace-Jeroen-Hautekeete** [comment]
Hi - yes ... it's for dt.entities.list(...) - I'm trying to use an entitySelector that can return multiple different custom_device types on the same relationship type.
