### ISSUE TITLE
Issue in Exporting logs through API

### ISSUE THREAD

**Issue by rajeshmoyra22** [dynatrace-oss/api-client-python#87]
** Description**
I am using dt-1.1.64 version to export log following guideline https://docs.dynatrace.com/docs/dynatrace-api/environment-api/log-monitoring-v2/git-export-logs
I have created Dynatrace instance using API token having 'Read logs' scope along with other scope.  Tried to read simple log using below command
logs = dt.logs.export(time_from="now-10m" )
logs = dt.logs.export("loglevel=\"ERROR\"")

**Expected behavior**
Dynatrace log should be exported 

**Screenshots**
Getting error 'HTTP ERROR 501 Not Implemented'

 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 501 Not Implemented</title>
</head>
<body><h2>HTTP ERROR 501 Not Implemented</h2>
<table>
<tr><th>URI:</th><td>/api/v2/logs/export</td></tr>
<tr><th>STATUS:</th><td>501</td></tr>
<tr><th>MESSAGE:</th><td>Not Implemented</td></tr>
</table>

</body>
![Registered_Error](https://github.com/user-attachments/assets/b549930d-2e0c-4c86-a3c2-d5090da1538a)

**Additional context**

**Comment by rajeshmoyra22** [comment]
I have seen similar issue has been reported in community - https://community.dynatrace.com/t5/Dynatrace-API/Issue-in-fetching-logs-through-API/m-p/246938#M3172

Kindly suggest a solution.

**Comment by Dynatrace-James-Kitson** [comment]
Most likely, if you make this same API call independent of this project (e.g. using curl or the API explorer) you'll get the same response. You should check this and reach out to support/chat to determine if you are able to use this API and if not why. If it doesn't work when manually interacting with this, the python client won't work either.
