### ISSUE TITLE
I am trying to implement the section for creating a Maintenance Window with Scope.

### ISSUE THREAD

**Issue by mmackenna** [dynatrace-oss/api-client-python#91]
**Is your feature request related to a problem? Please describe.**
I want to limit my maintenance windows to a list of hosts based on tags. This doesn't seem possible, as the client's scope object is incomplete.
This is an example of what I would like to be able to do with the scope section commented out.
```
    window = dt.maintenance_windows.create(
        name=window_name,
        description=window_description,
        window_type="PLANNED",
        suppression="DETECT_PROBLEMS_DONT_ALERT",
        schedule=sch,
        #scope=scope,
    )
    print(f"The maintenance window {window_name} has been created")
    return window
```

When I try to create a Scope object, it fails.
https://github.com/dynatrace-oss/api-client-python/blob/main/dynatrace/configuration_v1/maintenance_windows.py#L49

```
from dynatrace.configuration_v1.maintenance_windows import Scope, MonitoredEntityFilter
>>> scope = Scope(dt)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/mmackenna/python/pynatrace/.venv/lib/python3.11/site-packages/dynatrace/dynatrace_object.py", line 35, in __init__
    self._create_from_raw_data(raw_element)
  File "/Users/mmackenna/python/pynatrace/.venv/lib/python3.11/site-packages/dynatrace/configuration_v1/maintenance_windows.py", line 52, in _create_from_raw_data
    self.matches: Optional[List[MonitoredEntityFilter]] = [MonitoredEntityFilter(raw_element=m) for m in raw_element.get("matches")]
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Describe the solution you'd like**
I would like a method for creating a scope like there is one for creating a schedule.
sch = dt.maintenance_windows.create_schedule("ONCE", now, end, zone_id)
https://github.com/dynatrace-oss/api-client-python/blob/main/dynatrace/configuration_v1/maintenance_windows.py#L73

**Describe alternatives you've considered**
I tried instantiating a Scope object by passing it a dictionary and other objects. I have yet to be successful.

**Additional context**
I would consider additional documentation with an example of how to do this as a good alternative to implementation.

**Comment by Dynatrace-James-Kitson** [comment]
Hi Michael - this is possible with the API/this project but we've mostly stopped making changes to some of the endpoints like Maintenance Windows because those have been deprecated in favor of the settings API which has replaced it (see the note on https://docs.dynatrace.com/docs/shortlink/api-maintenance-windows). And if you use the '...' and select API for a maintenance window in the UI it will show you some things like the schema values you would use with this endpoint.

There is a simple example of using the settings API (for creating a metric event) in the readme examples which may help.
